### PR TITLE
Add warning and tip containers for attachments

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Tell me if you like the idea/if you want to change things.

Screen Shot 2021-02-11 at 16 12 43

I'll do the same changes in French after confirmation.

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
Preview: https://cds-snc.github.io/notification-documentation/review-apps/warning-tip-sending-files/c93c1f/en/send.html#sending-a-file-by-email

**Comment by anikbrazeau** [comment]
This is great, thank you! 
Let's do it!

**Comment by AntoineAugusti** [comment]
Did the same in French and darken the colour of the title in the warning block for a11y

**Review by anikbrazeau — APPROVED** [review]
Amazing! 🚀

**Pull request merged**
