### PR TITLE
feat: add back to Notify links on landing

### PR DESCRIPTION
**Pull request by AntoineAugusti**

### CODE REVIEW

**Review by anikbrazeau — APPROVED** [review]
Something to consider: Do we need this page? if we have `/en` and `/fr`? could the `/` default to the browser language and content directly?

**Comment by AntoineAugusti** [comment]
@anikbrazeau Fantastic idea. Did just that in the last commit, are you able to be redirected to the French version with a browser in French. Any other preferred language will redirect to English.

**Comment by AntoineAugusti** [comment]
Review app link https://cds-snc.github.io/notification-documentation/review-apps/back-to-notify-landing/62139c/ (you'll be redirected just after visiting)

**Review by willeybryan — APPROVED** [review]
lgtm

**Pull request merged**
